version: "3"
services: 
  buongiorno:
    container_name: buongiorno-be
    image: meelunae/buongiorno-be
    restart: always
    build: .
    ports:
      - "1337:1337"
    links: 
      - mongo
  mongo: 
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
